import turtle
import random
tim = turtle.Turtle()
jack = turtle.Turtle()

#background
tim.pensize(5)
tim.color("black","black")
tim.begin_fill()
tim.up()
tim.forward(632)
tim.down()
tim.right(90)
tim.forward(320)
tim.right(90)
tim.speed(11)
tim.forward(1270)
tim.right(90)
tim.forward(645)
tim.right(90)
tim.forward(1270)
tim.right(90)
tim.forward(325)
tim.end_fill()
#background

#star
for x in range(50):
    tim.pensize(1)
    tim.color("khaki","khaki")
    tim.up()
    tim.goto(random.randrange(-600, 600),random.randrange(-300, 300))
    tim.down()
    tim.left(144)
    tim.begin_fill()
    for x in range(5):
        tim.right(144)
        tim.forward(6)
    tim.end_fill()
    #   
    tim.color("white","white")
    tim.up()
    tim.goto(random.randrange(-600, 600),random.randrange(-300, 300))
    tim.down()
    tim.left(144)
    tim.begin_fill()
    tim.circle(1)
    tim.end_fill()
    #
    tim.color("plum", "plum")
    tim.up()
    tim.goto(random.randrange(-600, 600),random.randrange(-300, 300))
    tim.down()
    tim.left(144)
    tim.begin_fill()
    tim.circle(2)
    tim.end_fill()
    #
    tim.color("crimson", "crimson")
    tim.up()
    tim.goto(random.randrange(-600, 600),random.randrange(-300, 300))
    tim.down()
    tim.left(144)
    tim.begin_fill()
    tim.circle(1)
    tim.end_fill()
    #
    tim.color("royalblue","royalblue")
    tim.up()
    tim.goto(random.randrange(-600, 600),random.randrange(-300, 300))
    tim.down()
    tim.left(144)
    tim.begin_fill()
    for x in range(5):
        tim.right(144)
        tim.forward(3)
    tim.end_fill()    
#star


tim.color("red")
jack.color("white")
tim.pensize(3)
jack.pensize(3)
tim.up()

#A
tim.goto(0,0)
tim.speed(2)
jack.speed(2)
tim.down()
tim.left(90)
tim.forward(20)
jack.forward(20)
tim.left(90)
jack.right(90)
tim.forward(40)
jack.forward(40)
tim.left(90)
tim.forward(40)
tim.left(90)
jack.up()
jack.goto(0,0)
jack.down()
jack.right(90)
tim.forward(80)
jack.forward(20)

#P&C
tim.pencolor("white")
jack.pencolor("white")
tim.up()
jack.up()
tim.goto(-80,-40)
jack.goto(80,40)
tim.down()
jack.down()
tim.right(180)
jack.forward(40)
tim.forward(80)
jack.left(90)
tim.right(90)
jack.forward(80)
tim.forward(40)
tim.right(90)
jack.left(90)
tim.forward(40)
jack.forward(40)
tim.right(90)
tim.forward(40)

#A&C
tim.up()
jack.up()
tim.goto(-140,-40)
jack.forward(20)
tim.down()
jack.down()
tim.right(180)
jack.left(90)
tim.forward(40)
jack.forward(80)
tim.left(90)
jack.right(90)
tim.forward(40)
jack.forward(40)
tim.left(90)
jack.right(90)
tim.forward(40)
jack.up()
jack.forward(40)
jack.down()
jack.right(90)
jack.forward(40)
tim.right(90)
jack.left(90)
tim.forward(40)
jack.forward(40)
tim.right(90)
jack.left(90)
tim.forward(40)
jack.forward(40)








   
turtle.done()